// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZk-ue-CmzyNKXYc8Bh6dXOssuJo-iGdo',
    appId: '1:926761046669:web:9e6c6ebc568e611d4308c4',
    messagingSenderId: '926761046669',
    projectId: 'football-match-e1831',
    authDomain: 'football-match-e1831.firebaseapp.com',
    storageBucket: 'football-match-e1831.appspot.com',
    measurementId: 'G-R17TDG37PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl1UX_0MHiFm6ESiYBDcu0D25P_EHb9Fg',
    appId: '1:926761046669:android:25327061723a3a1d4308c4',
    messagingSenderId: '926761046669',
    projectId: 'football-match-e1831',
    storageBucket: 'football-match-e1831.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM0--Hh754G6uFvrKgjQl1FLKmpTsvcCk',
    appId: '1:926761046669:ios:08d39b08b22b121e4308c4',
    messagingSenderId: '926761046669',
    projectId: 'football-match-e1831',
    storageBucket: 'football-match-e1831.appspot.com',
    iosClientId: '926761046669-b6j7ijhknfg8maoa8rcditaog6610pgk.apps.googleusercontent.com',
    iosBundleId: 'com.example.spodApp',
  );
}
